language: go

go:
    - "1.5.1"

env:
    global:
        - SSH_KEY="travis"
        - GIT_NAME="elgris"
        - GIT_EMAIL="iddqd07@yandex.ru"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

before_install:
- openssl aes-256-cbc -K $encrypted_f94914cc10ea_key -iv $encrypted_f94914cc10ea_iv
  -in travis.enc -out travis -d

install::
    - go get -u -v github.com/spf13/hugo

script:
    - hugo

after_success:
    - ./scripts/deploy.sh